export const JUDGE_SCHEMA = {
  type:"object",
  additionalProperties:false,
  properties:{
    decision:{type:"string",enum:["accept","ambiguous","abstain"]},
    top5:{
      type:"array",
      maxItems:5,
      items:{
        type:"object",
        additionalProperties:false,
        properties:{
          candidate_id:{type:"string"},
          confidence:{type:"number",minimum:0,maximum:1},
          reason:{type:"string"}
        },
        required:["candidate_id","confidence","reason"]
      }
    },
    summary:{type:"string"},
    warnings:{type:"array",items:{type:"string"},maxItems:10}
  },
  required:["decision","top5","summary","warnings"]
};
