export const RANKING_SCHEMA = {
  type:"object",
  additionalProperties:false,
  properties:{
    rankings:{
      type:"array",
      maxItems:12,
      items:{
        type:"object",
        additionalProperties:false,
        properties:{
          candidate_id:{type:"string"},
          score:{type:"number",minimum:0,maximum:1},
          matched:{type:"array",items:{type:"string"},maxItems:12},
          conflicts:{type:"array",items:{type:"string"},maxItems:10},
          unknown:{type:"array",items:{type:"string"},maxItems:10},
          reason:{type:"string"}
        },
        required:["candidate_id","score","matched","conflicts","unknown","reason"]
      }
    },
    summary:{type:"string"},
    ambiguous:{type:"boolean"},
    warnings:{type:"array",items:{type:"string"},maxItems:10}
  },
  required:["rankings","summary","ambiguous","warnings"]
};
